version: '3.3'

services:
  
  backend:
    container_name: tinymlaasbackend
    build:
      context: .
      dockerfile: backend.Dockerfile
    command: uvicorn main:app --host 0.0.0.0
    ports: 
      - 8000:8000
    privileged: true
    environment:
      - DATABASE_URL=sqlite:///./tiny_mlaas.db 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - 0.0.0.0:8501:8501
    environment:
      - BACKEND_URL=http://tinymlaasbackend:8000
      - ROBOT_TESTS=${ROBOT}

networks:
  default:
    name: tinyml_network