version: '3.3'

services:

  
  backend:
    container_name: tinymlaasbackend
    build:
      context: .
      dockerfile: backend_no_tf.Dockerfile
    runtime: sysbox-runc
    hostname: syscont
    ports: 
      - 8000:8000
    environment:
      - DATABASE_URL=sqlite:///./tiny_mlaas.db
    
  
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - 0.0.0.0:8501:8501
    environment:
      - BACKEND_URL=http://tinymlaasbackend:8000
      - ROBOT_TESTS=${ROBOT}
    privileged: true
    volumes:
     - /dev/bus/usb:/dev/bus/usb

networks:
  default:
    name: tinyml_network
