version: '3.3'

services:
  
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports: 
      - 0.0.0.0:8000:8000
  
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - 0.0.0.0:8501:8501
    environment:
      - BACKEND_URL=http://backend:8000
  
