project:
  type: website

format:
  html:
    theme: lux
    css: styles.css
    toc: true

website:
  title: "TinyMLaaS"
  twitter-card: true
  open-graph: true
  repo-url: "https://github.com/TinyMLaas"
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
  sidebar:
    style: floating

metadata-files: [nbdev.yml, sidebar.yml]
