name: Repo
on: repository_dispatch

jobs:
  Run-robot-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./docker-compose.yml"
          up-flags: "-d"
        env:
          ROBOT: "true"
      - name: Setup chromedriver
        uses: nanasess/setup-chromedriver@master
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
      - name: Clone repository
        run: |
          git clone https://github.com/TinyMLaas/TinyML-frontend.git
      - name: Install dependecies
        working-directory: ./TinyML-frontend
        run: pip install -r requirements.txt
      - name: Run robot tests
        working-directory: ./TinyML-frontend
        run: python -m robot -d robot_output tests/
      
  Deploy:
    if: (needs.Run-robot-tests == 'success')
    needs: Run-robot-tests
    runs-on: ubuntu-latest
    steps:
     - name: connect
       uses: appleboy/ssh-action@v0.1.10
       with:
        host: ${{ secrets.SSH_HOST_1 }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWD }}
        sync: true
        script: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST_2 }} "./deploy.sh ${{ secrets.SERVER_USER_PASSWD }}"
          
