name: Repo
on: repository_dispatch

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
     - name: connect
       uses: appleboy/ssh-action@v0.1.10
       with:
        host: ${{ secrets.SSH_HOST_1 }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWD }}
        sync: true
        script: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST_2 }} "./deploy.sh ${{ secrets.SERVER_USER_PASSWD }}"
          
