name: Repo
on: repository_dispatch

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    # - name: install ssh keys
      # run: |
      #    install -m 600 -D /dev/null ~/.ssh/id_rsa
      #    echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
      #    ssh-keyscan -H ${{ secrets.SSH_HOST_1 }} > ~/.ssh/known_hosts
     - name: connect
       run: |
          sshpass -p ${{ secrets.SSH_PASSWD }} ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST_1 }}
      #    ssh ${{ secrets.SSH_USER }}@{{ secrets.SSH_HOSTS_2 }}
     #- name: Change to correct user and go to wanted directory
     #  run: |
     #     ../../login.sh
     #     ${{ secrets.SERVER_USER_PASSWD }}
     #     cd TinyMLaaS
      #- name: build and deploy
      #  run: |
      #    docker compose build --no-cache
      #    docker compose up -d
     - name: Disconenct and cleanup
       run: |
        exit
        exit
        rm -rf ~/.ssh
          
